### ISSUE TITLE
Advice on integration with Hyper

### ISSUE THREAD

**Issue by cmusser** [benashford/redis-async-rs#4] opened 2017-12-09 21:25 UTC
I'm looking for advice on how to use the async-redis client in a Hyper server. This isn't really an issue or a bug, so hopefully this is an appropriate forum.

Not sure how familiar you are with Hyper, but the idea is that a Tokio reactor::Core is handed a TCP listener that returns a stream of incoming connections . Each incoming request is passed the core's handle and a Hyper "service" object that satisfies the request. Specifically, this is done in a function named "call()", which is part of the "service" trait. It's the job of "call()" to return a future that resolves the request. 

Right now, my service uses a fie;d in the request to look up data in an in-memory HashMap and base its response on that data (or lack thereof). The HashMap is what I'd like to replace with a lookup against the Redis server.

I'm not sure how to approach this. I think the basic idea is:

1. Store a reference to the Redis connection in the service object instance when it's created. Since creating the object involves a future, I'm not sure how to work this into the constructor function for my service.

2. Inside call(), use the connection reference to send a a request to Redis and, in the returned future, read the answer and then create and return the response future that Hyper needs.

Do you have examples of this kind of usage or advice on how to structure the code, perhaps differently than what I've described above? I tried to adapt one of the example programs to do a simple send a GET and read the response, but I had numerous troubles getting it to compile.

**Comment by benashford** [comment] 2017-12-10 16:59
Hello,

Thanks for this.  I'm not familiar with the newer versions of Hyper (the async versions), although it is definitely on my list, and the goal of `redis-async-rs` is to be compatible with everything that uses Tokio.

The issue, in a nutshell, seems to be that `reds-async-rs` exposes a quite low-level API, even the API I describe as "high-level" in the README, is still lower-level than Hyper.  I'm sure the two would be compatible, as `redis-async-rs` should be able to use Hyper's reactor (although it doesn't have to).  The issue is knowing where best to connect everything.

The Hello World example Hyper offers hides the reactor, but this can be exposed, as per this example: https://github.com/hyperium/hyper/blob/master/examples/multi_server.rs

By manually creating the reactor first, the kind of approach you describe should work.

Regarding your question about opening a Redis connection returning a future.  This is because that is itself an asynchronous operation, before any commands are passed.  This could be resolved by potentially chaining the futures, creating the Hyper server can be in an `and_then` after the Redis connection has been opened.

But that previous sentence is me thinking out-loud as I haven't yet tried combining this library with others.  I'm also very willing (it's why this is still a `v0.x` version) to change the external API if it makes interoperability easier, being idiomatic is an important goal.

I'm going to leave this issue open as a placeholder for myself to add some interoperability examples to the project to work out these edges.

**Comment by cmusser** [comment] 2017-12-10 20:13
Right, the reactor can be created beforehand. I do that in my server now and the example of yours that I was studying does so as well. After a bit of experimentation, I made a small isolated example that performs the operation my application needs: a "GET" for a single  value. It's based on examples/monitor.rs, which was an easy-to-understand starting point. The meat of it is:

```
     let mut core = Core::new().unwrap();

     let addr: SocketAddr =(format!("{}:6379", redis_server).to_string()).parse().unwrap();

     let getter = client::connect(&addr, &core.handle())
         .map_err(|e| e.into())
         .and_then(|connection| {
             let client::ClientConnection { sender, receiver } = connection;
             sender
                 .send(resp_array!["GET", url])
                 .map_err(|e| e.into())
                 .and_then(move |_| {
                     receiver.take(1).for_each(|answer| {
                         println!("{:?}", answer);
                         future::ok(())
                     })
                 })
         });
     
     core.run(getter).unwrap();
```
One observation is that a stream construct might not be appropriate for all cases. If you imagine this code existing in the context of the Hyper service `call()` function, it only wants to deal with the a
response to the request it just made, not handle a stream of responses. I've made it do that by using `take().for_each()` to get a single answer. It's a little awkward, but not intolerable.

I guess a larger question would be: using a single connection to the Redis server, but operating in an asynchronous fashion as demonstrated here, is it guaranteed that the response I obtain corresponds to the request performed by the `sender.send()`? I wonder if I could run into a situation where they weren't matched and then the response object I create for Hyper would be for a different user request.

**Comment by benashford** [comment] 2017-12-10 20:58
For this kind of thing the `paired_connect` is the better option, as it pairs the request and the response for you.  Using `connect`, as you say, does run the risk of mismatched results; `connect` is only really suitable for "single threaded" situations, like the `MONITOR` example.

Internally `paired_connect` works by putting every command into a queue, so they'll be sent to Redis in the same order as `send` is called (which may be unpredictable from an external vantage point, due to it being called asynchronously, but internally will be deterministic), and returns a `futures::sync::oneshot`.  Redis supports pipelining and will return the answers in the same order, so when the responses come back the appropriate `oneshot`s are satisfied.

The important restriction to this is that it only works with commands that have single responses to single commands, so calling `MONITOR` or any of the PUBSUB commands would produce nonsensical answers.  But essentially everything else, `GET`, `SET`, `SMEMBERS`, etc., fall into the safe category.

Updating your example, it should work with minor modification:

```rust
let getter = client::paired_connect(&addr, &core.handle())
         .map_err(|e| e.into())
         .and_then(|connection| {
             connection
                 .send(resp_array!["GET", url])
                 .map_err(|e| e.into())
                 .and_then(|answer: String|
                     println!("{:?}", answer);
                     future::ok(()))
         });

```

**Comment by cmusser** [comment] 2017-12-10 23:27
Tried a variation of your `paired_connect` version, but unfortunately bogged down trying to get it to compile.

I think there are some curly braces missing in the closure handed to the innermost `and_then()`. An amended version is below, but it doesn't compile due to type inference problems. This is what I ended up with:

```
    let getter = client::paired_connect(&addr, &core.handle())
         .map_err(|e| e.into())
         .and_then(|connection| {
             connection
                 .send(resp_array!["GET", url])
                 .map_err(|e| e.into())
                 .and_then(|answer: String| {
                     println!("{:?}", answer);
                           future::ok(())
                 })
         });
```
The error is:
```
49 |     let getter = client::paired_connect(&addr, &core.handle())
   |         ------ consider giving `getter` a type
50 |          .map_err(|e| e.into())
   |           ^^^^^^^ cannot infer type for `E`
```
I tried doing what the compiler suggested by doing this
```
let getter: Box<Future<Item = PairedConnection, Error = Error>> = Box<Future<Item = PairedConnection, Error = Error>> = client::paired_connect(&addr, &core.handle());
    getter
    // The rest of the chain is here...
```
That left me with the same "cannot infer type" mesage, but without the "consider giving" suggestion. I tried to type annotate the map_err() call several different ways, to no avail. This is a more general "how to Rust" question. If you know how to fix this up, great, but I'll continue experimenting with it.

**Comment by benashford** [comment] 2017-12-11 16:08
The futures returned by `redis-async-rs` all have one of these as the error type: https://github.com/benashford/redis-async-rs/blob/master/src/error.rs#L20-L38 but, of course, this will be specific to a Redis client.  Hyper will do something similar, and a system that used both will almost certainly have its own error mechanism.

The message you're getting seems to suggest it doesn't know how to convert one type of error to another.  If there is a conversion trait defined between the two error types then `e.into()` should work.  Otherwise removing the `.map_err...` line entirely will give you a more concrete error message, which will help track-down what's missing.

**Comment by cmusser** [comment] 2017-12-11 20:34
Taking out the `map_err()` looked to be the solution at first. I think the reason is that the return from `client::paired_connect()` is a Box, which does not have a `map_err()` function, even though the enclosed future does. My understanding of this is very hazy.

The sample "retrieve value for a key" program compiles and works now. However integrating the Redis connection creation into the startup for the hyper server is proving difficult. This is what I tried:

```
fn run_service(addr: &SocketAddr, redis_addr: &SocketAddr, service: MyService) {
    let http = Http::new();
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    let listener = client::paired_connect(redis_addr, &handle)
        .and_then(|connection| {
            let listener = net2::TcpBuilder::new_v4().unwrap()
                .reuse_port(true).unwrap()
                .bind(addr).unwrap()
                .listen(128).unwrap();
            
            let l = TcpListener::from_listener(listener, addr, &handle).unwrap();
            l.incoming().for_each(|(socket, addr)| {
                http.bind_connection(&handle, socket, addr, service.clone());
                Ok(())
            })
        });

    core.run(listener).unwrap();
}
```

Here, the errors are:
```
   |
28 |         .and_then(|connection| {
   |          ^^^^^^^^ expected struct `std::io::Error`, found enum `redis_async::error::Error`
   |
   = note: expected type `std::io::Error`
              found type `redis_async::error::Error`

rror[E0271]: type mismatch resolving `<futures::stream::ForEach<tokio_core::net::Incoming, [closure@src/svc.rs:35:35: 38:14 http:_, handle:_, service:_], std::result::Result<(), std::io::Error>> as futures::IntoFuture>::Error == redis_async::error::Error`
  --> src/svc.rs:41:10
   |
41 |     core.run(listener).unwrap();
   |          ^^^ expected struct `std::io::Error`, found enum `redis_async::error::Error`
   |
   = note: expected type `std::io::Error`
              found type `redis_async::error::Error`
   = note: required because of the requirements on the impl of `futures::Future` for `futures::AndThen<std::boxed::Box<futures::Future<Error=redis_async::error::Error, Item=redis_async::client::PairedConnection>>, futures::stream::ForEach<tokio_core::net::Incoming, [closure@src/svc.rs:35:35: 38:14 http:_, handle:_, service:_], std::result::Result<(), std::io::Error>>, [closure@src/svc.rs:28:19: 39:10 addr:_, handle:_, http:_, service:_]>`

```

Which is interesting. It's seems like it *needs* a way to map the error into something that `core.run()` expects. Back in the sample program, I'd tried to use a construct like this, to fix the `cannot infer type for 'E'` error, but to no avail:
```
      .map_err(|e: redis_async::error::Error| e.into())
```

**Comment by benashford** [comment] 2017-12-11 21:02
This does make an amount of sense, if I'm understanding it correctly.

The problem in a nutshell is that a Future has two types, the type of the successful value and the type of the error value.  The closure in an `and_then` call can change the type of the successful value, but errors still occur if the type of the error do not match.  So the error type of the `for_each` on the incoming socket is `std::io::Error`, but the error type on the Redis calls is `redis_async::error::Error`.

A quick test for this would be to add a `.map_err` on the future returned by `paired_connect` that created a fake `std::io::Error` regardless of the underlying error.  This would be functionally invalid and poor error handling, but it would test the type signatures.  This way all the futures would have `std::io::Error` as the error type and the compiler should be happy.

As for no `.map_err` on `paired_connect` - there should be 🤔.  This is where Rust's type-system, as clever and as useful as it is, can turn into quite a puzzle as the error messages aren't as helpful as they could be.  I have had similar problems before, which turned out to be caused by me forgetting to import the right traits into my module, do you have a `use futures::Future` in this module?  But if it was that I'd expect `.and_then` not to work either.  Alternatively it could be because of the type signature problems meaning an appropriate implementation couldn't be found, the fake error in the previous paragraph should test that too.

If that works, the full solution is probably to convert all errors to a type thats specific to your app.  You may define a `RequestError` for example, that would also satisfy the chain of futures as each level would be returning the same type.

**Comment by cmusser** [comment] 2017-12-12 17:22
I misspoke regarding the lack of `map_err`. Once you specify types in the right way, it compiles. I don't fully understand what the difficulty was with the type inference, but this is what I came up with for integrating the Redis connection sequence into the startup of the service:

```
    let http = Http::new();
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    let listener = client::paired_connect(redis_addr, &handle)
        .map_err(|e: redis_async::error::Error| std::io::Error::new(ErrorKind::Other,
                                                                    format!("{:?}", e)))
        .and_then(|connection| {
            let listener = net2::TcpBuilder::new_v4().unwrap()
                .reuse_port(true).unwrap()
                .bind(addr).unwrap()
                .listen(128).unwrap();

            let svc = MyService::new(Arc::new(connection), data, counters);
            let l = TcpListener::from_listener(listener, addr, &handle).unwrap();
            l.incoming().for_each(move |(socket, addr)| {
                http.bind_connection(&handle, socket, addr, svc.clone());
                Ok(())
            })
        });

    core.run(listener).unwrap();
```

At this point, the connection object is in the service object. When Hyper invokes the service's `call()` method, it can use that connection to do the Redis lookup. How to do that (in lieu of my current "look up data in a local HashMap") I have not worked out yet. Currently, `call()` is parameterized to return a boxed future containing a `hyper::Response`, so I need to understand how to produce that at resolution of the Redis query.

**Comment by cmusser** [comment] 2017-12-12 21:54
This is looking to be rough sledding. The idea is to convert the current lookup and response creation, which is this:

```
Box::new(futures::future::ok(match self.redirects.find(fqdn) {
    Some(redirect) => self.found_fqdn_response(fqdn, uri_path, &redirect),
    None => {
        self.update_response_count(ResponseType::NotFound);
        self.unavailable_page(fqdn)
    },
}))
```

To something approximately like this:

```
Box::new(self.connection
         .send(resp_array!["GET", fqdn])
         .map_err(|e: redis_async::error::Error| hyper::Error::Status)
         .map(|answer| {
             match answer {
                 RespValue::BulkString(found) => {
                     let redirect: Redirect = serde_json::from_slice(&found).unwrap();
                     let r = redirect.clone();
                     println!("{:?}", redirect);
                     self.found_fqdn_response(fqdn, uri_path, &r)
                 },
                 RespValue::Nil => {
                     self.update_response_count(ResponseType::NotFound);
                     self.unavailable_page(fqdn)
                 },
                 _ => {
                     println!("unexpected value: {:?}", answer);
                     self.update_response_count(ResponseType::NotFound);
                     self.unavailable_page(fqdn)
                 }
             }
         }))
```

The above runs into lifetime problems. This particular error is vexing,: I simply can't infer from the messages what's wrong and how to fix it.

``` 
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
   --> src/service.rs:204:25
    |
204 | /                         Box::new(self.connection
205 | |                                  .send(resp_array!["GET", fqdn])
206 | |                                  .map_err(|e: redis_async::error::Error| hyper::Error::Status)
207 | |                                  .map(|answer| {
...   |
224 | |                                      }
225 | |                                  }))
    | |____________________________________^
    |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the body at 195:49...
   --> src/service.rs:195:50
    |
195 |       fn call(&self, req: Request) -> Self::Future {
    |  __________________________________________________^
196 | |         let uri_path = req.uri().path();
197 | |         match uri_path {
198 | |             ADS_PAGE => Box::new(futures::future::ok(self.ads_page())),
...   |
234 | |         }
235 | |     }
    | |_____^
note: ...so that the type `futures::Map<futures::MapErr<std::boxed::Box<futures::Future<Error=redis_async::error::Error, Item=redis_async::resp::RespValue>>, [closure@src/service.rs:206:43: 206:94]>, [closure@src/service.rs:207:39: 225:35 self:&&service::HoptoService, fqdn:&&str, uri_path:&&str]>` will meet its required lifetime bounds
   --> src/service.rs:204:25
    |
204 | /                         Box::new(self.connection
205 | |                                  .send(resp_array!["GET", fqdn])
206 | |                                  .map_err(|e: redis_async::error::Error| hyper::Error::Status)
207 | |                                  .map(|answer| {
...   |
224 | |                                      }
225 | |                                  }))
    | |____________________________________^
    = note: but, the lifetime must be valid for the static lifetime...
note: ...so that expression is assignable (expected std::boxed::Box<futures::Future<Error=hyper::Error, Item=hyper::Response> + 'static>, found std::boxed::Box<futures::Future<Error=hyper::Error, Item=hyper::Response>>)
   --> src/service.rs:204:25
    |
204 | /                         Box::new(self.connection
205 | |                                  .send(resp_array!["GET", fqdn])
206 | |                                  .map_err(|e: redis_async::error::Error| hyper::Error::Status)
207 | |                                  .map(|answer| {
...   |
224 | |                                      }
225 | |                                  }))
    | |____________________________________^
```

**Comment by benashford** [comment] 2017-12-12 22:25
At a quick glance, I think it's complaining because the Box returned contains a closure with a reference to `self` (e.g. the call to `found_fqdn_response`), but there's no guarantee that `self` will be around (due to it being asynchronous) and that only static references are safe to be captured by that particular closure (so that the Box can be assigned when it's received by the calling function, the lifetime of the Box cannot be known at compile time).

Could it be refactored in a way that doesn't need a reference to `self`?

**Comment by cmusser** [comment] 2017-12-12 23:27
I think you're right. As a quick check, I replaced the statements in those match arms with hardwired responses and it compiled and ran (and, as an aside, the Redis lookups worked correctly). I've been tripped up in the past by closures capturing more than I'd intended before, and this looks to be another case of that.

It looks like some refactoring and diving into lifetimes is needed. The "create a response" methods part of the service and they depend on some internal state stored there: a cache of page templates and a collection of stats counters. That state is long lived,  so there may be a way of specifying lifetimes on it in such a way that the compiler is assured that it's not going away. This may take some time to work out, but I'll report back.

**Comment by cmusser** [comment] 2017-12-14 18:45
Some sort of artful reference to a long-lifetimed object is probably the most efficient way, but I did come up with a workable solution: clone the "self" object and other things needed in the closure, then have the closure take ownership with move.

This isn't optimal, but cloning the self object, which contains a small number of `Arc` wrapped fields that do implement clone efficiently, isn't the worst thing in the world.
 
The snippet in question, which resides inside `call()` function required by the Hyper `Service` trait:

```
let service = self.clone();
let uri_path = uri_path.to_string();
let key = host.hostname();
let fqdn = key.to_string();

Box::new(self.connection
         .send(resp_array!["GET", key])
         .map_err(|_: redis_async::error::Error| hyper::Error::Status)
         .map( |answer| {
             match answer {
                 RespValue::BulkString(found) => {
                     let redirect: Redirect = serde_json::from_slice(&found).unwrap();
                     service.found_fqdn_response(&fqdn, &uri_path, &redirect)
                 },
                 RespValue::Nil => {
                     service.update_response_count(ResponseType::NotFound);
                     service.unavailable_page(&fqdn)
                 },
                 _ => {
                     println!("unexpected value: {:?}", answer);
                     service.update_response_count(ResponseType::NotFound);
                     service.unavailable_page(&fqdn)
                 }
             }
         }))
``` 

With this, the service works as it did before, but uses Redis, not internally managed data. One optimization would be to store the values as raw Rust structures, rather than as small JSON documents which have to be deserialized on every retrieval. Perhaps CBOR would be a more efficient serialization format. But that's a task for the program that loads the data (a separate entity).

**Comment by benashford** [comment] 2018-02-11 16:32
Closing this issue now, as I think we've covered all the topics it raises.  Feel free to raise any future issues if required.

**Closed by benashford** 2018-02-11 16:32 UTC
